Create working link_toggle bash script.

diff --git a/link_replace b/link_replace
--- a/link_replace
+++ b/link_replace
@@ -33,10 +33,12 @@ else
   echo "Link path cannot be found." >&2
   exit 2
 fi
-if [[ -e "${TARGET_PATH}" ]]; then
+if [[ -e "$(realpath ${TARGET_PATH})" ]]; then
+  # Use real path or else result will depend on directory user is in when calling script.
   :
 else
-  echo "New target path invalid." >&2
+  # echo "New target path invalid." >&2
+  echo "New target path invalid: ${TARGET_PATH}" >&2
   exit 2
 fi
 # if [[ "${TARGET_PATH}" == $(realpath "${EXISTING_LINK_PATH}") ]]; then
@@ -50,13 +52,13 @@ SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 cd "${SCRIPT_DIR}"
 python <<< "import link_update as lu ; lu.replace_link_target('${EXISTING_LINK_PATH}', '${TARGET_PATH}', ${RELATIVE})"
 # https://unix.stackexchange.com/questions/533156/using-python-in-a-bash-script
+PYTHON_RETURN=$? # gets return value of last command executed.
+
 cd - > /dev/null # suppress outputs
 
-
-PYTHON_RETURN=$? # gets return value of last command executed.
 # Make sure the program ran correctly
 if [ ${PYTHON_RETURN} -ne 0 ]; then
-	printf "\nSomething went wrong in Python call to link_upate.replace_link_target().\n"
+	printf "\nSomething went wrong in Python call to link_update.replace_link_target().\n"
 	exit 1
 fi
 
